server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          oidc-provider:
            client-id: ${OIDC_CLIENT_ID}
            client-secret: ${OIDC_CLIENT_SECRET}
            scope: openid, profile, email, groups
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          oidc-provider:
            issuer-uri: ${OIDC_ISSUER_URI}
