# Disable in-memory mode and use file-based storage in /app/data
spring.datasource.url=jdbc:h2:file:/app/data/homelab_db;DB_CLOSE_ON_EXIT=TRUE;WRITE_DELAY=0;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=us
spring.datasource.password=us

# Set JPA update mode so schema persists
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect